services:
  - docker

env:
  global:
  - USER="juliankamil"
  - EMAIL="julian.kamil@gmail.com"
  - REPO="emma-deploy"
  - UPDATE="update.txt"
  - GH_REPO="github.com/${USER}/${REPO}.git"

before_install:
  - docker build -t fourpione/nginx:latest .  
  
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fourpione/nginx:latest

after_success:
  - git clone git://github.com/juliankamil/emma-deploy.git
  - cd emma-deploy
  - touch update.txt
  - echo "#$TRAVIS_BUILD_NUMBER" > update.txt
  - git remote
  - git config user.email julian.kamil@gmail.com
  - git config user.name juliankamil
  - git add .
  - git commit -m "New images from build #$TRAVIS_BUILD_NUMBER"
  - git push "https://${GH_TOKEN}@github.com/juliankamil/emma-deploy.git" master > /dev/null 2>&1
