services:
  - docker

before_install:
  - docker build -t fourpione/nginx:latest .  
  
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fourpione/nginx:latest

after_success:
  - .travis/push.sh
