services:
  - docker

before_install:
  - docker build -t fourpione/nginx:latest .  
  
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --pasword-stdin
  - docker push fourpione/nginx:latest
