services:
  - docker

env:
  global:
  - USER="juliankamil"
  - EMAIL="julian.kamil@gmail.com"
  - REPO="emma-deploy"
  - UPDATE="update.txt"
  - GH_REPO="github.com/${USER}/${REPO}.git"

before_install:
  - docker build -t fourpione/nginx:latest .  
  
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fourpione/nginx:latest

after_success:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - git clone git://${GH_REPO}
  - cd ${REPO}
  - touch ${UPDATE}
  - git remote
  - git config user.email ${EMAIL}
  - git config user.name ${USER}
  - git add ${UPDATE}
  - git commit -m ${MESSAGE}
  - git push "https://${GH_TOKEN}@${GH_REPO}" master > /dev/null 2>&1
